### ISSUE TITLE
Linkedin Login Error

### ISSUE THREAD

**Issue by himanshumahajan04** [zyra/cordova-plugin-linkedin#11] opened 2017-05-11 14:03 UTC
I am getting issue with Linkedin integration in app. I am following Ionic 2 documentation for integrating linkedin:

https://ionicframework.com/docs/native/linkedin/

hasActiveSession() method returns true even if I have deleted Linkedin app from device. And, how I can fetch user related information If user has active session?

Ideally, if Linkedin app is deleted from device then hasActiveSession() method should return false.

**Comment by ihadeed** [comment] 2017-05-17 18:35
So if I understand correctly, to reproduce this I have to:
1. Login with LinkedIn
2. Uninstall LinkedIn app
3. Call `hasActiveSession()`

**Comment by himanshumahajan04** [comment] 2017-05-18 08:02
Yes, and once you call hasActiveSession() method after uninstalling Linkedin app, it returns true.

**Comment by ihadeed** [comment] 2017-05-19 06:24
@himanshumahajan04 

I can't really do anything on my end. This plugin simply wraps the LinkedIn SDKs. So the behavior you're experiencing is how they designed the SDK to behave. 

I believe if there is an active session you can use other methods like `getRequest` and `postRequest` since there is a valid access token in the system. 

If you're still experiencing issues and you need to make sure that the app is installed before continuing, I recommend using the App Availability plugin https://ionicframework.com/docs/native/app-availability/ .

I'm closing this issue since there's nothing that can be done here to "fix" it.

**Closed by ihadeed** 2017-05-19 06:24 UTC
